import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const haskoy = localFont({
  src: "../assets/fonts/haskoy[wght].woff2",
  display: "swap",
  variable: "--font-haskoy",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={haskoy.className}>
      <body>{children}</body>
    </html>
  );
}
